FROM node:20-alpine

WORKDIR /app

# Copia apenas dependências primeiro (cache mais eficiente)
COPY package*.json ./

RUN npm install

# Copia restante do projeto
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]