services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env_prod
    volumes:
      - static_volume:/staticfiles
    networks:
      - net_sales

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
    networks:
      - net_sales

networks:
  net_sales:

volumes:
  pg_data:
  static_volume: