services:
  db:
    image: postgres:18-alpine
    container_name: sales_db
    restart: always
    networks:
      - interface
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sales_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - interface
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sales_frontend
    networks:
      - interface
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true      

networks: 
  interface:
    driver: bridge